//
// Created by ale on 27/10/16.
//

#ifndef RESTAURANTCONCURRENTE_LOCKFILES_H_H
#define RESTAURANTCONCURRENTE_LOCKFILES_H_H

#define SEM_CLIENTES_LIVING_FILE "CMakeCache.txt"
#define SEM_CLIENTES_LIVING_LETRA 'z'
#define SM_CLIENTES_LIVING_FILE "/bin/bash"
#define SM_CLIENTES_LIVING_LETRA 'z'

#define SM_CAJA_FILE "/bin/cat"
#define SM_CAJA_LETRA 'A'
#define SEM_CAJA_FILE "/bin/echo"
#define SEM_CAJA_LETRA 'z'

#define SM_DINERO_PERDIDO_FILE "/bin/tar"
#define SM_DINERO_PERDIDO_LETRA 'b'
#define SEM_DINERO_PERDIDO_FILE "/bin/cp"
#define SEM_DINERO_PERDIDO_LETRA 'k'

#define SM_TIRAR_PEDIDOS_MESAS_FILE "/bin/dir"
#define SM_TIRAR_PEDIDOS_MESAS_LETRA 'a'












#endif //RESTAURANTCONCURRENTE_LOCKFILES_H_H
